import Head from 'next/head'
import { Container, Text, Spacer } from "@nextui-org/react"
import LoginButton from '../components/LoginButton'
import AccessDenied from '../components/accessDenied'
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession()


  if(!session) { return <AccessDenied/> }

  return (
    <div>
      <Head>
        <title>Next Auth Testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Spacer />
           <Text h1>Auth Test</Text>
           <Text h2>Signed in as {session.user.name}</Text>
        <LoginButton />
      </Container>

     
      
    </div>
  )
}
