import Head from 'next/head'
import { Container, Text, Spacer } from "@nextui-org/react"
import LoginButton from '../components/LoginButton'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Auth Testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Spacer />
           <Text h1>Auth Test</Text>
        <LoginButton />
      </Container>

     
      
    </div>
  )
}
