import Head from 'next/head'
import { Container, Typography } from "@nextui-org/react"
import LoginButton from '../components/LoginButton'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1>Auth Test</h1>
        <LoginButton />
      
    </div>
  )
}
